// <auto-generated />
using DataAccessLayer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("MasterSchema")
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusinessLogic.Models.Category", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("catName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("catOrder")
                        .HasColumnType("int");

                    b.Property<bool>("markedAsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("isDeleted");

                    b.HasKey("id");

                    b.HasIndex("catName");

                    b.ToTable("Categories", "MasterSchema");

                    b.HasData(
                        new
                        {
                            id = 1,
                            catName = "Category 1",
                            catOrder = 1,
                            markedAsDeleted = false
                        },
                        new
                        {
                            id = 2,
                            catName = "Category 2",
                            catOrder = 2,
                            markedAsDeleted = false
                        },
                        new
                        {
                            id = 3,
                            catName = "Category 3",
                            catOrder = 3,
                            markedAsDeleted = false
                        },
                        new
                        {
                            id = 4,
                            catName = "Category 4",
                            catOrder = 4,
                            markedAsDeleted = false
                        },
                        new
                        {
                            id = 5,
                            catName = "Category 5",
                            catOrder = 5,
                            markedAsDeleted = false
                        },
                        new
                        {
                            id = 6,
                            catName = "Category 6",
                            catOrder = 6,
                            markedAsDeleted = false
                        },
                        new
                        {
                            id = 7,
                            catName = "Category 7",
                            catOrder = 7,
                            markedAsDeleted = false
                        },
                        new
                        {
                            id = 8,
                            catName = "Category 8",
                            catOrder = 8,
                            markedAsDeleted = false
                        },
                        new
                        {
                            id = 9,
                            catName = "Category 9",
                            catOrder = 9,
                            markedAsDeleted = false
                        },
                        new
                        {
                            id = 10,
                            catName = "Category 10",
                            catOrder = 10,
                            markedAsDeleted = false
                        });
                });

            modelBuilder.Entity("BusinessLogic.Models.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("author")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("categoryId")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("markedAsDeleted")
                        .HasColumnType("bit");

                    b.Property<double>("price")
                        .HasColumnType("float")
                        .HasColumnName("BookPrice");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.HasIndex("categoryId");

                    b.ToTable("Products", "MasterSchema");

                    b.HasData(
                        new
                        {
                            id = 1,
                            author = "Author 1",
                            categoryId = 1,
                            markedAsDeleted = false,
                            price = 11.5,
                            title = "Product 1"
                        },
                        new
                        {
                            id = 2,
                            author = "Author 2",
                            categoryId = 1,
                            markedAsDeleted = false,
                            price = 22.0,
                            title = "Product 2"
                        },
                        new
                        {
                            id = 3,
                            author = "Author 3",
                            categoryId = 1,
                            markedAsDeleted = false,
                            price = 32.5,
                            title = "Product 3"
                        },
                        new
                        {
                            id = 4,
                            author = "Author 4",
                            categoryId = 2,
                            markedAsDeleted = false,
                            price = 12.5,
                            title = "Product 4"
                        },
                        new
                        {
                            id = 5,
                            author = "Author 5",
                            categoryId = 2,
                            markedAsDeleted = false,
                            price = 23.0,
                            title = "Product 5"
                        },
                        new
                        {
                            id = 6,
                            author = "Author 6",
                            categoryId = 2,
                            markedAsDeleted = false,
                            price = 33.5,
                            title = "Product 6"
                        },
                        new
                        {
                            id = 7,
                            author = "Author 7",
                            categoryId = 3,
                            markedAsDeleted = false,
                            price = 13.5,
                            title = "Product 7"
                        },
                        new
                        {
                            id = 8,
                            author = "Author 8",
                            categoryId = 3,
                            markedAsDeleted = false,
                            price = 24.0,
                            title = "Product 8"
                        },
                        new
                        {
                            id = 9,
                            author = "Author 9",
                            categoryId = 3,
                            markedAsDeleted = false,
                            price = 34.5,
                            title = "Product 9"
                        },
                        new
                        {
                            id = 10,
                            author = "Author 10",
                            categoryId = 4,
                            markedAsDeleted = false,
                            price = 14.5,
                            title = "Product 10"
                        },
                        new
                        {
                            id = 11,
                            author = "Author 11",
                            categoryId = 4,
                            markedAsDeleted = false,
                            price = 25.0,
                            title = "Product 11"
                        },
                        new
                        {
                            id = 12,
                            author = "Author 12",
                            categoryId = 4,
                            markedAsDeleted = false,
                            price = 35.5,
                            title = "Product 12"
                        },
                        new
                        {
                            id = 13,
                            author = "Author 13",
                            categoryId = 5,
                            markedAsDeleted = false,
                            price = 15.5,
                            title = "Product 13"
                        },
                        new
                        {
                            id = 14,
                            author = "Author 14",
                            categoryId = 5,
                            markedAsDeleted = false,
                            price = 26.0,
                            title = "Product 14"
                        },
                        new
                        {
                            id = 15,
                            author = "Author 15",
                            categoryId = 5,
                            markedAsDeleted = false,
                            price = 36.5,
                            title = "Product 15"
                        },
                        new
                        {
                            id = 16,
                            author = "Author 16",
                            categoryId = 6,
                            markedAsDeleted = false,
                            price = 16.5,
                            title = "Product 16"
                        },
                        new
                        {
                            id = 17,
                            author = "Author 17",
                            categoryId = 6,
                            markedAsDeleted = false,
                            price = 27.0,
                            title = "Product 17"
                        },
                        new
                        {
                            id = 18,
                            author = "Author 18",
                            categoryId = 6,
                            markedAsDeleted = false,
                            price = 37.5,
                            title = "Product 18"
                        },
                        new
                        {
                            id = 19,
                            author = "Author 19",
                            categoryId = 7,
                            markedAsDeleted = false,
                            price = 17.5,
                            title = "Product 19"
                        },
                        new
                        {
                            id = 20,
                            author = "Author 20",
                            categoryId = 7,
                            markedAsDeleted = false,
                            price = 28.0,
                            title = "Product 20"
                        },
                        new
                        {
                            id = 21,
                            author = "Author 21",
                            categoryId = 7,
                            markedAsDeleted = false,
                            price = 38.5,
                            title = "Product 21"
                        },
                        new
                        {
                            id = 22,
                            author = "Author 22",
                            categoryId = 8,
                            markedAsDeleted = false,
                            price = 18.5,
                            title = "Product 22"
                        },
                        new
                        {
                            id = 23,
                            author = "Author 23",
                            categoryId = 8,
                            markedAsDeleted = false,
                            price = 29.0,
                            title = "Product 23"
                        },
                        new
                        {
                            id = 24,
                            author = "Author 24",
                            categoryId = 8,
                            markedAsDeleted = false,
                            price = 39.5,
                            title = "Product 24"
                        },
                        new
                        {
                            id = 25,
                            author = "Author 25",
                            categoryId = 9,
                            markedAsDeleted = false,
                            price = 19.5,
                            title = "Product 25"
                        },
                        new
                        {
                            id = 26,
                            author = "Author 26",
                            categoryId = 9,
                            markedAsDeleted = false,
                            price = 30.0,
                            title = "Product 26"
                        },
                        new
                        {
                            id = 27,
                            author = "Author 27",
                            categoryId = 9,
                            markedAsDeleted = false,
                            price = 40.5,
                            title = "Product 27"
                        },
                        new
                        {
                            id = 28,
                            author = "Author 28",
                            categoryId = 10,
                            markedAsDeleted = false,
                            price = 20.5,
                            title = "Product 28"
                        },
                        new
                        {
                            id = 29,
                            author = "Author 29",
                            categoryId = 10,
                            markedAsDeleted = false,
                            price = 31.0,
                            title = "Product 29"
                        },
                        new
                        {
                            id = 30,
                            author = "Author 30",
                            categoryId = 10,
                            markedAsDeleted = false,
                            price = 41.5,
                            title = "Product 30"
                        });
                });

            modelBuilder.Entity("BusinessLogic.Models.Product", b =>
                {
                    b.HasOne("BusinessLogic.Models.Category", "category")
                        .WithMany("products")
                        .HasForeignKey("categoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");
                });

            modelBuilder.Entity("BusinessLogic.Models.Category", b =>
                {
                    b.Navigation("products");
                });
#pragma warning restore 612, 618
        }
    }
}
